# Generated by Django 3.1.4 on 2020-12-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='price',
        ),
    ]
