# Generated by Django 3.1.4 on 2020-12-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_dish_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category_id',
        ),
    ]
