# Generated by Django 3.1.4 on 2020-12-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_dish_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category_id',
            field=models.ManyToManyField(to='menu.Category'),
        ),
    ]
