# Generated by Django 3.1.4 on 2020-12-28 17:43

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_dish_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category_id',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.category'),
        ),
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default=1, upload_to=menu.models.Dish.get_file_name_dishes),
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
